version: '3'
services:
  web-application:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./web-application:/web-application
    environment:
      - FLASK_ENV=production
      - FLASK_APP=server.py