"""update

Revision ID: 591934ec02d0
Revises: 7437ae61d786
Create Date: 2024-10-27 04:48:03.158069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '591934ec02d0'
down_revision: Union[str, None] = '7437ae61d786'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('balance_after', sa.Numeric(precision=15, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'balance_after')
    # ### end Alembic commands ###
