"""Added the status column on bank account

Revision ID: 7105780189ec
Revises: d2ef6d652339
Create Date: 2024-10-27 22:42:57.804616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7105780189ec'
down_revision: Union[str, None] = 'd2ef6d652339'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('status', sa.VARCHAR(length=25), nullable=True))
    # ### end Alembic commands ###
