"""Added the status column on bank account

Revision ID: d2ef6d652339
Revises: 591934ec02d0
Create Date: 2024-10-27 22:40:25.231767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2ef6d652339'
down_revision: Union[str, None] = '591934ec02d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bank_accounts', sa.Column('status', sa.String(length=25), nullable=True))
    op.add_column('transactions', sa.Column('status', sa.String(length=25), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'status')
    op.drop_column('bank_accounts', 'status')
    # ### end Alembic commands ###
